### PR TITLE
Begin of Nord Theme (WIP)

### PR DESCRIPTION
**Pull request by Paraxdev**
WIP version of an additional theme based on the Nord color scheme.
Screenshots of the test version currently:
image
image
image

### CODE REVIEW

**Comment by TCNOco** [comment]
This looks great! Excited to see how it turns out.

**Comment by Paraxdev** [comment]
The latest commit as some QoL and small tweaks to the design

- Nord colors now are stored as SCSS variables, everything else is normal CSS
- Text input is now similar to windows fluent UI (details in screenshot)
- Hovering over an active or selected account now makes the border solid, while the hovered element is marked with a bottom border

TODO:
Remove or rearrange the CSS code to make it a bit more pleasant to the eyes (I'm fairly new to CSS, so I will try my best)

Screenshots:
image
image
image
image
image

**Comment by Paraxdev** [comment]
If possible @TcNobo can you try it out and report any findings you might make?

**Comment by Paraxdev** [comment]
The CSS Part is done, what I need to do now is the markdown

**Comment by TCNOco** [comment]
Awesome. Looks great! I will be merging now, and including in the next release of the app. Thanks a ton!

**Pull request merged**
